os: linux
dist: focal
arch: amd64

language: python

python:
  - "3.8"

env:
  - GO_VERSION=1.21.5

git:
  depth: 1

before_install:
- wget https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz
- sudo tar -xvf go${GO_VERSION}.linux-amd64.tar.gz
- sudo mv go /usr/local
- export GOROOT=/usr/local/go
- export GOPATH=$HOME/go
- export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
- go install github.com/mattn/goveralls@latest
- openssl aes-256-cbc -K $encrypted_8bed37950213_key -iv $encrypted_8bed37950213_iv -in client-secret.json.enc -out client-secret.json -d

before_deploy:
- curl 'https://goreportcard.com/checks' -d 'repo=github.com%2Frfinochi%2Fgolang-workshop-todo'
- rm ./.github/ISSUE_TEMPLATE/bug_report.md
- rm ./docs/docs.go
- rm ./docs/swagger.json
- rm ./docs/swagger.yaml
- rm ./LICENSE
- rm ./README.md
- rm ./OSSMETADATA
- rm ./.travis.yml
- rm ./client-secret.json.enc
- rm ./docker-compose.yml
- rm ./Makefile
- rm ./Web.config
- cp ./cmd/web/application.go ./application.go
- cp ./cmd/web/handlers.go ./handlers.go
- cp ./cmd/web/main.go ./main.go
- cp ./cmd/web/middleware.go ./middleware.go
- cp ./cmd/web/REVISION ./REVISION
- cp ./cmd/web/routes.go ./routes.go
- rm ./cmd/web/application.go
- rm ./cmd/web/handlers_test.go
- rm ./cmd/web/handlers.go
- rm ./cmd/web/main_test.go
- rm ./cmd/web/main.go
- rm ./cmd/web/middleware.go
- rm ./cmd/web/REVISION
- rm ./cmd/web/routes.go
- rmdir ./cmd/web
- rmdir ./cmd
- rmdir ./.github/ISSUE_TEMPLATE
- rmdir ./.github
- echo $TRAVIS_BUILD_NUMBER > REVISION
- go install github.com/swaggo/swag/cmd/swag@latest
- swag init

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - go version
  - python --version
  - $GOPATH/bin/goveralls -service=travis-ci

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

services:
  - mongodb

deploy:
  skip_cleanup: true
  provider: gae
  keyfile: client-secret.json
  project: golang-workshop-todo
